### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by dpryan79** [fredeBio/REALPHY#3]
Two quick questions regarding the license:

 - Is redistribution allowed? That is, should projects like Bioconda be able to redistribute trivially installable copies?
 - What is explicitly intended by "for internal, research purposes"? Can one publish results obtained from realphy?

**Comment by fredeBio** [comment]
Yes, redistribution is allowed and yes, I am also very happy for REALPHY to be redistributed by Bioconda.
Yes, results obtained from REALPHY can be published.

**Comment by dpryan79** [comment]
Great, thanks for the prompt reply!
